name: first workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on : ubuntu-latest
    steps:
      - name: first_step
        run : echo "hello navi"
      - name : second_step
        run: echo "step 2"
        
    
